name: CI

on:
  push:
    branches: [ master ]

    workflow_dispatch:
    
jobs:
    display:
      runs-on: ubuntu-latest
      env:
        TOKEN: ${{secrets.TOKEN}}

      steps:
        - name: Display custom environment variables
          run: |
            echo "le token est ${{ env.TOKEN }}"
